l1nx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import RedirectView, TemplateView

from l1nx import views
from l1nx_blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    re_path(r'^$', views.index, name="home"),
    re_path(r'^admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('l1nx_blog.urls', namespace='l1nx_blog'), name='l1nx_blog'),
    path('monitor/', include('monitor.urls', namespace='monitor'), name='monitor'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += [
    path('logout/', views.logout_view, name='logout'),
    re_path(r'^complete/instagram/$', views.connect_inst, name='instagram-complete'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

l1nx_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView, TemplateView

from l1nx_blog import views

app_name='l1nx_blog'

urlpatterns = [
    re_path(r'^$', views.PostListView.as_view(), name='post_list'),
    re_path(r'^(?P<tag>[-\w]+)/$', views.PostListView.as_view(), name='post_tag'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

l1nx_blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Не опубликовано'),
        ('published', 'Опубликовано'),
    )
    title = models.CharField(verbose_name='название', max_length=255, blank=False)
    slug = models.SlugField(verbose_name='путь', max_length=255, blank=False)
    author = models.ForeignKey(User, verbose_name='автор', related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField(verbose_name='содержание', blank=False)
    date_publish = models.DateTimeField(verbose_name='дата публикации', default=timezone.now)
    date_created = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    date_updated = models.DateTimeField(verbose_name='дата обновления', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Статья блога'
        verbose_name_plural = 'Статьи блога'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('l1nx_blog:post_detail', args=[self.date_publish.year, self.date_publish.strftime('%m'), self.date_publish.strftime('%d'), self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(verbose_name='Опубликован', default=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return 'Комментарий {} к посту {}'.format(self.author, self.post)

l1nx_blog/forms.py
from django import forms

from l1nx_blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

l1nx_blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.auth.models import User
from taggit.models import Tag

from l1nx_blog.models import Post, Comment
from l1nx_blog.forms import EmailPostForm, CommentForm


class PostListView(ListView):
    queryset = Post.objects.filter(status='published')
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'l1nx_blog/list.html'
    tag_slug = None

    def get_queryset(self):
        qs = self.queryset
        if self.tag_slug:
            tag = get_object_or_404(Tag, slug=self.tag_slug)
            qs = qs.filter(tags__in=[tag])
        return qs

    def get(self, request, *args, **kwargs):
        if 'tag' in kwargs:
            self.tag_slug = kwargs['tag']
        return super().get(request, *args, **kwargs)



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', date_publish__year=year, date_publish__month=month, date_publish__day=day)
    comments = post.comments.filter(active=True)
    user = User.objects.filter(username=request.user).first()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids, status='published').exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-date_publish')[:4]

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = user
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,'l1nx_blog/detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) рекомендует к просмотру "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Читайте "{}" на сайте {}\n\n{} оставил комментарий: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'l1nx_blog/share.html', {'post': post, 'form': form, 'sent': sent})

l1nx_blog/templates/l1nx_blog/detail.html
{% extends 'l1nx/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="page-layout">
    <div class="content"> 
            <h1>{{ post.title }}</h1>
            <p class="date">
                Published {{ post.date_publish }} by {{ post.author }}
            </p>
            {{ post.body|linebreaks }}
            {% if post.tags.exists %}
                <p class="tags">
                    Теги:
                    {% for tag in post.tags.all %}
                        <a href="{% url "l1nx_blog:post_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            {% endif %}
            {% with comments.count as total_comments %}
                <h2>
                    {{ total_comments }} comment{{ total_comments|pluralize }}
                </h2>
            {% endwith %}
            {% for comment in comments %}
                <div class="comment">
                    <p class="info">
                        Комментарий {{ forloop.counter }} от <strong>{{ comment.author }}</strong>
                        {{ comment.created|date:'d.m.Y' }}
                    </p>
                    {{ comment.body|linebreaks }}
                </div>
            {% empty %}
                <p>Ещё никто не оставил комментарий. Будьте первым!</p>
            {% endfor %}
            {% if request.user.is_authenticated %}
                {% if new_comment %}
                    <h2>Ваш комментарий опубликован.</h2>
                {% else %}
                    <h2>Оставить комментарий</h2>
                    <form action="." method="post">
                        {{ comment_form.as_p }}
                        {% csrf_token %}
                        <p><input type="submit" value="Добавить комментарий"></p>
                    </form>
                {% endif %}
            {% endif %}
            <p>
                <a href="{% url "l1nx_blog:post_share" post.id %}">Поделитесь этим постом</a>
            </p>
            <h2>Похожие статьи</h2>
            {% for post in similar_posts %}
                <p>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </p>
            {% empty %}
                Похожих постов не найдено.
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

l1nx_blog/templates/l1nx_blog/list.html
{% extends 'l1nx/base.html' %}
{% block title %}Блог{% endblock title%}
{% block content %}
<div class="page-layout">
    <div class="content">
        <h2>Блог</h2>
        <div class="blog_post__list">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}"><h3>{{post.title}}</h3></a>
            <p>{{ post.body|truncatewords:30|linebreaks }}</p>
            {% if post.tags.exists %}
                <p class="tags">
                    Теги:
                    {% for tag in post.tags.all %}
                        <a href="{% url "l1nx_blog:post_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            {% endif %}
            <span>{{post.author}} - {{post.date_publish|date:"d m Y"}}</span>
        {% endfor %}
        </div>
        {% include "l1nx_blog/pagination.html" with page=page_obj %}
    </div>
</div>
{% endblock content %}

l1nx_blog/templates/l1nx_blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

l1nx_blog/templates/l1nx_blog/share.html
{% extends "l1nx/base.html" %}
{% block title %}Поделиться постом{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлен</h1>
        <p>
            "{{ post.title }}" был успешно отправлен {{ cd.to }}.
        </p>
    {% else %}
        <h1>Поделись "{{ post.title }}" по e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить">
        </form>
    {% endif %}
{% endblock %}